import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/custom/Header";
import { cn } from "@/lib/utils";
import QueryProvider from "@/utils/QueryProvider";
import StoreProvider from "@/utils/StoreProvider";
import { Toaster } from "@/components/ui/sonner";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={cn(
            "min-h-screen bg-background font-manrope antialiased",
            manrope.variable
          )}
        >
          <QueryProvider>
            <Header />
            <main>{children}</main>
            <Toaster dir="ltr" duration={5000} position="top-center" />
          </QueryProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
